//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionController
    {
        public int ActionControllerId { get; set; }
        public string ActionControllerCode { get; set; }
        public string ActionControllerName { get; set; }
    }
}
