//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMRDBEntities : DbContext
    {
        public EMRDBEntities()
            : base("name=EMRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionController> ActionControllers { get; set; }
        public virtual DbSet<ActionControllerRole> ActionControllerRoles { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<HostState> HostStates { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<UserEntityMapping> UserEntityMappings { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
