//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostState
    {
        public int HostStateId { get; set; }
        public string HostStateCode { get; set; }
        public string HostStateName { get; set; }
        public Nullable<int> PasswordResetTime { get; set; }
        public Nullable<int> PasswordLockedTime { get; set; }
    }
}
