//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IsActive { get; set; }
        public string IsLocked { get; set; }
        public Nullable<System.DateTime> LastLoginAttemptDate { get; set; }
        public Nullable<System.DateTime> LastPasswordResetDate { get; set; }
        public Nullable<System.DateTime> LastUserLockedTime { get; set; }
        public Nullable<int> FailedPasswordCount { get; set; }
        public string IsStaff { get; set; }
    }
}
