//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.DS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntityMapping
    {
        public int UserEntityMappingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string EntityType { get; set; }
    }
}
